import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_variants_shipping_mode" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum__variants_v_version_shipping_mode" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum_products_shipping_mode" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum__products_v_version_shipping_mode" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum_carts_items_shipping_mode_snapshot" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum_orders_items_shipping_mode_snapshot" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum_orders_shipping_mode" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum_orders_shipping_provider" AS ENUM('tapin', 'manual');
  CREATE TYPE "public"."enum_orders_shipping_status" AS ENUM('manual_coordination', 'quoted', 'shipment_pending', 'creating', 'created', 'in_transit', 'delivered', 'failed');
  CREATE TYPE "public"."enum_transactions_items_shipping_mode_snapshot" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum_transactions_shipping_mode" AS ENUM('parcel', 'freight');
  CREATE TYPE "public"."enum_transactions_shipping_provider" AS ENUM('tapin', 'manual');
  ALTER TABLE "variants" ADD COLUMN "shipping_mode" "enum_variants_shipping_mode" DEFAULT 'freight';
  ALTER TABLE "variants" ADD COLUMN "parcel_weight_in_grams" numeric;
  ALTER TABLE "variants" ADD COLUMN "tapin_box_i_d" numeric;
  ALTER TABLE "_variants_v" ADD COLUMN "version_shipping_mode" "enum__variants_v_version_shipping_mode" DEFAULT 'freight';
  ALTER TABLE "_variants_v" ADD COLUMN "version_parcel_weight_in_grams" numeric;
  ALTER TABLE "_variants_v" ADD COLUMN "version_tapin_box_i_d" numeric;
  ALTER TABLE "products" ADD COLUMN "shipping_mode" "enum_products_shipping_mode" DEFAULT 'freight';
  ALTER TABLE "products" ADD COLUMN "parcel_weight_in_grams" numeric;
  ALTER TABLE "products" ADD COLUMN "tapin_box_i_d" numeric;
  ALTER TABLE "_products_v" ADD COLUMN "version_shipping_mode" "enum__products_v_version_shipping_mode" DEFAULT 'freight';
  ALTER TABLE "_products_v" ADD COLUMN "version_parcel_weight_in_grams" numeric;
  ALTER TABLE "_products_v" ADD COLUMN "version_tapin_box_i_d" numeric;
  ALTER TABLE "carts_items" ADD COLUMN "shipping_mode_snapshot" "enum_carts_items_shipping_mode_snapshot" DEFAULT 'freight';
  ALTER TABLE "carts_items" ADD COLUMN "parcel_weight_in_grams_snapshot" numeric;
  ALTER TABLE "carts_items" ADD COLUMN "tapin_box_i_d_snapshot" numeric;
  ALTER TABLE "orders_items" ADD COLUMN "shipping_mode_snapshot" "enum_orders_items_shipping_mode_snapshot" DEFAULT 'freight';
  ALTER TABLE "orders_items" ADD COLUMN "parcel_weight_in_grams_snapshot" numeric;
  ALTER TABLE "orders_items" ADD COLUMN "tapin_box_i_d_snapshot" numeric;
  ALTER TABLE "orders" ADD COLUMN "shipping_mode" "enum_orders_shipping_mode" DEFAULT 'freight';
  ALTER TABLE "orders" ADD COLUMN "shipping_amount_in_t_m_n" numeric DEFAULT 0;
  ALTER TABLE "orders" ADD COLUMN "shipping_provider" "enum_orders_shipping_provider" DEFAULT 'manual';
  ALTER TABLE "orders" ADD COLUMN "shipping_service_i_d" varchar;
  ALTER TABLE "orders" ADD COLUMN "shipping_service_label" varchar;
  ALTER TABLE "orders" ADD COLUMN "shipping_province_code" numeric;
  ALTER TABLE "orders" ADD COLUMN "shipping_city_code" numeric;
  ALTER TABLE "orders" ADD COLUMN "shipping_weight_in_grams" numeric;
  ALTER TABLE "orders" ADD COLUMN "shipping_box_i_d" numeric;
  ALTER TABLE "orders" ADD COLUMN "shipping_quoted_at" timestamp(3) with time zone;
  ALTER TABLE "orders" ADD COLUMN "shipping_status" "enum_orders_shipping_status" DEFAULT 'manual_coordination';
  ALTER TABLE "orders" ADD COLUMN "shipping_shipment_i_d" varchar;
  ALTER TABLE "orders" ADD COLUMN "shipping_tracking_code" varchar;
  ALTER TABLE "orders" ADD COLUMN "shipping_provider_status" varchar;
  ALTER TABLE "orders" ADD COLUMN "shipping_failure_message" varchar;
  ALTER TABLE "orders" ADD COLUMN "shipment_created_at" timestamp(3) with time zone;
  ALTER TABLE "transactions_items" ADD COLUMN "shipping_mode_snapshot" "enum_transactions_items_shipping_mode_snapshot" DEFAULT 'freight';
  ALTER TABLE "transactions_items" ADD COLUMN "parcel_weight_in_grams_snapshot" numeric;
  ALTER TABLE "transactions_items" ADD COLUMN "tapin_box_i_d_snapshot" numeric;
  ALTER TABLE "transactions" ADD COLUMN "shipping_mode" "enum_transactions_shipping_mode" DEFAULT 'freight';
  ALTER TABLE "transactions" ADD COLUMN "shipping_amount_in_t_m_n" numeric DEFAULT 0;
  ALTER TABLE "transactions" ADD COLUMN "shipping_provider" "enum_transactions_shipping_provider" DEFAULT 'manual';
  ALTER TABLE "transactions" ADD COLUMN "shipping_service_i_d" varchar;
  ALTER TABLE "transactions" ADD COLUMN "shipping_service_label" varchar;
  ALTER TABLE "transactions" ADD COLUMN "shipping_province_code" numeric;
  ALTER TABLE "transactions" ADD COLUMN "shipping_city_code" numeric;
  ALTER TABLE "transactions" ADD COLUMN "shipping_weight_in_grams" numeric;
  ALTER TABLE "transactions" ADD COLUMN "shipping_box_i_d" numeric;
  ALTER TABLE "transactions" ADD COLUMN "shipping_quoted_at" timestamp(3) with time zone;
  CREATE UNIQUE INDEX "orders_shipping_shipment_i_d_idx" ON "orders" USING btree ("shipping_shipment_i_d");
  CREATE INDEX "orders_shipping_tracking_code_idx" ON "orders" USING btree ("shipping_tracking_code");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP INDEX "orders_shipping_shipment_i_d_idx";
  DROP INDEX "orders_shipping_tracking_code_idx";
  ALTER TABLE "variants" DROP COLUMN "shipping_mode";
  ALTER TABLE "variants" DROP COLUMN "parcel_weight_in_grams";
  ALTER TABLE "variants" DROP COLUMN "tapin_box_i_d";
  ALTER TABLE "_variants_v" DROP COLUMN "version_shipping_mode";
  ALTER TABLE "_variants_v" DROP COLUMN "version_parcel_weight_in_grams";
  ALTER TABLE "_variants_v" DROP COLUMN "version_tapin_box_i_d";
  ALTER TABLE "products" DROP COLUMN "shipping_mode";
  ALTER TABLE "products" DROP COLUMN "parcel_weight_in_grams";
  ALTER TABLE "products" DROP COLUMN "tapin_box_i_d";
  ALTER TABLE "_products_v" DROP COLUMN "version_shipping_mode";
  ALTER TABLE "_products_v" DROP COLUMN "version_parcel_weight_in_grams";
  ALTER TABLE "_products_v" DROP COLUMN "version_tapin_box_i_d";
  ALTER TABLE "carts_items" DROP COLUMN "shipping_mode_snapshot";
  ALTER TABLE "carts_items" DROP COLUMN "parcel_weight_in_grams_snapshot";
  ALTER TABLE "carts_items" DROP COLUMN "tapin_box_i_d_snapshot";
  ALTER TABLE "orders_items" DROP COLUMN "shipping_mode_snapshot";
  ALTER TABLE "orders_items" DROP COLUMN "parcel_weight_in_grams_snapshot";
  ALTER TABLE "orders_items" DROP COLUMN "tapin_box_i_d_snapshot";
  ALTER TABLE "orders" DROP COLUMN "shipping_mode";
  ALTER TABLE "orders" DROP COLUMN "shipping_amount_in_t_m_n";
  ALTER TABLE "orders" DROP COLUMN "shipping_provider";
  ALTER TABLE "orders" DROP COLUMN "shipping_service_i_d";
  ALTER TABLE "orders" DROP COLUMN "shipping_service_label";
  ALTER TABLE "orders" DROP COLUMN "shipping_province_code";
  ALTER TABLE "orders" DROP COLUMN "shipping_city_code";
  ALTER TABLE "orders" DROP COLUMN "shipping_weight_in_grams";
  ALTER TABLE "orders" DROP COLUMN "shipping_box_i_d";
  ALTER TABLE "orders" DROP COLUMN "shipping_quoted_at";
  ALTER TABLE "orders" DROP COLUMN "shipping_status";
  ALTER TABLE "orders" DROP COLUMN "shipping_shipment_i_d";
  ALTER TABLE "orders" DROP COLUMN "shipping_tracking_code";
  ALTER TABLE "orders" DROP COLUMN "shipping_provider_status";
  ALTER TABLE "orders" DROP COLUMN "shipping_failure_message";
  ALTER TABLE "orders" DROP COLUMN "shipment_created_at";
  ALTER TABLE "transactions_items" DROP COLUMN "shipping_mode_snapshot";
  ALTER TABLE "transactions_items" DROP COLUMN "parcel_weight_in_grams_snapshot";
  ALTER TABLE "transactions_items" DROP COLUMN "tapin_box_i_d_snapshot";
  ALTER TABLE "transactions" DROP COLUMN "shipping_mode";
  ALTER TABLE "transactions" DROP COLUMN "shipping_amount_in_t_m_n";
  ALTER TABLE "transactions" DROP COLUMN "shipping_provider";
  ALTER TABLE "transactions" DROP COLUMN "shipping_service_i_d";
  ALTER TABLE "transactions" DROP COLUMN "shipping_service_label";
  ALTER TABLE "transactions" DROP COLUMN "shipping_province_code";
  ALTER TABLE "transactions" DROP COLUMN "shipping_city_code";
  ALTER TABLE "transactions" DROP COLUMN "shipping_weight_in_grams";
  ALTER TABLE "transactions" DROP COLUMN "shipping_box_i_d";
  ALTER TABLE "transactions" DROP COLUMN "shipping_quoted_at";
  DROP TYPE "public"."enum_variants_shipping_mode";
  DROP TYPE "public"."enum__variants_v_version_shipping_mode";
  DROP TYPE "public"."enum_products_shipping_mode";
  DROP TYPE "public"."enum__products_v_version_shipping_mode";
  DROP TYPE "public"."enum_carts_items_shipping_mode_snapshot";
  DROP TYPE "public"."enum_orders_items_shipping_mode_snapshot";
  DROP TYPE "public"."enum_orders_shipping_mode";
  DROP TYPE "public"."enum_orders_shipping_provider";
  DROP TYPE "public"."enum_orders_shipping_status";
  DROP TYPE "public"."enum_transactions_items_shipping_mode_snapshot";
  DROP TYPE "public"."enum_transactions_shipping_mode";
  DROP TYPE "public"."enum_transactions_shipping_provider";`)
}
