import { Home, MapPin, Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { getAccountData } from "@/features/account/account-data";
import { requireUser } from "@/features/auth/session";
import { addAddressAction } from "../actions";

export default async function AddressesPage() {
  const user = await requireUser();
  const { addresses } = await getAccountData(user);
  return <div className="space-y-6"><section><p className="text-xs font-semibold text-wine">آدرس‌های من</p><h2 className="mt-2 text-2xl font-medium">نشانی‌های تحویل</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{addresses.map((address) => <article key={address.id} className="relative border border-black/10 bg-white p-5"><div className="flex items-start justify-between gap-4"><div className="grid size-10 place-items-center rounded-full bg-wine/7 text-wine">{address.title === "خانه" ? <Home className="size-4" /> : <MapPin className="size-4" />}</div>{address.isDefault ? <span className="border border-wine/20 bg-wine/5 px-2 py-1 text-[0.65rem] text-wine">پیش‌فرض</span> : null}</div><h3 className="mt-4 font-medium">{address.title}</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">{address.city}، {address.address}</p><div className="mt-4 border-t border-black/10 pt-4 text-xs text-muted-foreground"><p>{address.recipient}</p><p className="mt-1" dir="ltr">{address.phone}</p></div></article>)}</div></section><details className="group border border-black/10 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between p-5 font-medium [&::-webkit-details-marker]:hidden"><span className="flex items-center gap-2"><Plus className="size-4 text-wine" />افزودن آدرس جدید</span><span className="text-xs text-muted-foreground group-open:hidden">باز کردن فرم</span></summary><form action={addAddressAction} className="grid gap-4 border-t border-black/10 p-5 sm:grid-cols-2"><label className="text-sm">عنوان آدرس<input name="title" defaultValue="خانه" className="mt-2 h-11 w-full border border-black/15 px-3 outline-none focus:border-wine" /></label><label className="text-sm">نام تحویل‌گیرنده<input name="recipient" required defaultValue={user.name ?? ""} className="mt-2 h-11 w-full border border-black/15 px-3 outline-none focus:border-wine" /></label><label className="text-sm">شماره موبایل<input name="phone" required defaultValue={user.phone} dir="ltr" className="mt-2 h-11 w-full border border-black/15 px-3 text-left outline-none focus:border-wine" /></label><label className="text-sm">استان<input name="province" required className="mt-2 h-11 w-full border border-black/15 px-3 outline-none focus:border-wine" /></label><label className="text-sm">شهر<input name="city" required className="mt-2 h-11 w-full border border-black/15 px-3 outline-none focus:border-wine" /></label><label className="text-sm">کد پستی<input name="postalCode" inputMode="numeric" className="mt-2 h-11 w-full border border-black/15 px-3 outline-none focus:border-wine" /></label><label className="text-sm sm:col-span-2">نشانی کامل<textarea name="address" required rows={3} className="mt-2 w-full resize-none border border-black/15 p-3 outline-none focus:border-wine" /></label><Button type="submit" className="h-11 w-fit rounded-none bg-wine px-6 hover:bg-ink">ذخیره آدرس</Button></form></details></div>;
}
