/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus =
  ('pending_review' | 'confirmed' | 'in_production' | 'ready' | 'shipped' | 'delivered' | 'cancelled') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    'customer-otp-challenges': CustomerOtpChallenge;
    'customer-sessions': CustomerSession;
    media: Media;
    'blog-categories': BlogCategory;
    posts: Post;
    brands: Brand;
    projects: Project;
    categories: Category;
    'product-series': ProductSery;
    'configuration-groups': ConfigurationGroup;
    'configuration-options': ConfigurationOption;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      addresses: 'addresses';
      orders: 'orders';
    };
    'blog-categories': {
      posts: 'posts';
    };
    'configuration-groups': {
      options: 'configuration-options';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'customer-otp-challenges': CustomerOtpChallengesSelect<false> | CustomerOtpChallengesSelect<true>;
    'customer-sessions': CustomerSessionsSelect<false> | CustomerSessionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'product-series': ProductSeriesSelect<false> | ProductSeriesSelect<true>;
    'configuration-groups': ConfigurationGroupsSelect<false> | ConfigurationGroupsSelect<true>;
    'configuration-options': ConfigurationOptionsSelect<false> | ConfigurationOptionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: {
      cleanupDataTransferFiles: TaskCleanupDataTransferFiles;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers: Customer;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  phone?: string | null;
  role: 'admin' | 'editor' | 'seller';
  contactTitle?: string | null;
  contactDescription?: string | null;
  whatsappPhone?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName?: string | null;
  phone: string;
  active?: boolean | null;
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | Customer;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country: 'IR';
  phone?: string | null;
  displayLabel?: string | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        /**
         * ورودی پایدار گروه و گزینه؛ عنوان‌ها و شناسه نهایی در سرور بازنویسی می‌شوند.
         */
        configuration?:
          | {
              groupKey: string;
              group?: (number | null) | ConfigurationGroup;
              groupLabelFaSnapshot: string;
              option?: (number | null) | ConfigurationOption;
              optionCodeSnapshot?: string | null;
              labelFaSnapshot: string;
              id?: string | null;
            }[]
          | null;
        configurationKey: string;
        productTitleSnapshot: string;
        variantCodeSnapshot?: string | null;
        unitPriceInTMN: number;
        shippingModeSnapshot?: ('parcel' | 'freight') | null;
        parcelWeightInGramsSnapshot?: number | null;
        tapinBoxIDSnapshot?: number | null;
        id?: string | null;
      }[]
    | null;
  customer?: (number | null) | Customer;
  contactName: string;
  contactPhone: string;
  /**
   * این ارتباط خودکار است؛ جزئیات ثبت‌شده پایین، تصویر ثابت آدرس در زمان سفارش است.
   */
  customerAddress?: (number | null) | Address;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  deliveryMethod: 'advisor';
  shippingMode?: ('parcel' | 'freight') | null;
  shippingAmountInTMN?: number | null;
  shippingProvider?: ('tapin' | 'manual') | null;
  shippingServiceID?: string | null;
  shippingServiceLabel?: string | null;
  shippingProvinceCode?: number | null;
  shippingCityCode?: number | null;
  shippingWeightInGrams?: number | null;
  shippingBoxID?: number | null;
  shippingQuotedAt?: string | null;
  shippingStatus?:
    | (
        | 'manual_coordination'
        | 'quoted'
        | 'shipment_pending'
        | 'creating'
        | 'created'
        | 'in_transit'
        | 'delivered'
        | 'failed'
      )
    | null;
  shippingShipmentID?: string | null;
  shippingTrackingCode?: string | null;
  shippingProviderStatus?: string | null;
  shippingFailureMessage?: string | null;
  shipmentCreatedAt?: string | null;
  amount?: number | null;
  currency?: 'TMN' | null;
  paymentMethod: 'zarinpal' | 'invoice';
  paymentTransaction?: (number | null) | Transaction;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  orderNumber: string;
  sourceCart?: (number | null) | Cart;
  updatedAt: string;
  createdAt: string;
}
/**
 * پیش‌نمایش مدیریت محصول نیلپر؛ گونه‌های SKU از انتخاب‌های پارچه و رنگ چوب جدا هستند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  catalogCode?: string | null;
  brand: number | Brand;
  categories: (number | Category)[];
  series?: (number | null) | ProductSery;
  salesMode: 'direct' | 'inquiry' | 'made_to_order';
  availabilityMode: 'orderable' | 'in_stock' | 'unavailable';
  shippingMode?: ('parcel' | 'freight') | null;
  /**
   * وزن واقعی خود کالا؛ وزن بسته‌بندی عمومی از تنظیمات محرمانه تاپین افزوده می‌شود.
   */
  parcelWeightInGrams?: number | null;
  tapinBoxID?: number | null;
  priceInTMNEnabled?: boolean | null;
  priceInTMN?: number | null;
  mainImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        captionFa?: string | null;
        id?: string | null;
      }[]
    | null;
  descriptionFa: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * فقط اندازه‌های مشترک همه گونه‌ها؛ اندازه متفاوت هر کد ثبت در خود گونه نگهداری می‌شود.
   */
  measurements?:
    | {
        key: string;
        labelFa: string;
        value: number;
        unit: 'cm' | 'kg' | 'm' | 'unit';
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * مشخصاتی که برای همه گونه‌های این محصول یکسان‌اند.
   */
  technicalSpecs?:
    | {
        key: string;
        labelFa: string;
        valueFa: string;
        group: 'identity' | 'construction' | 'materials' | 'comfort' | 'finish' | 'delivery' | 'care' | 'other';
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  orderNotesFa?: string | null;
  leadTimeFa?: string | null;
  configurationGroups?: (number | ConfigurationGroup)[] | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * رابطه صریح برای محصولات یک ست یا خانواده؛ از پیشنهاد عمومی «محصولات مرتبط» جدا است.
   */
  matchingProducts?: (number | Product)[] | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  slug: string;
  descriptionFa?: string | null;
  taglineFa?: string | null;
  storyFa?: string | null;
  logo?: (number | null) | Media;
  heroMedia?: (number | null) | Media;
  heroAlt?: string | null;
  heroCaption?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  captionFa?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    adminThumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  descriptionFa?: string | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-series".
 */
export interface ProductSery {
  id: number;
  title: string;
  slug: string;
  styleFa?: string | null;
  descriptionFa?: string | null;
  heroMedia?: (number | null) | Media;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuration-groups".
 */
export interface ConfigurationGroup {
  id: number;
  title: string;
  key: string;
  inputType: 'swatch' | 'select' | 'radio';
  required?: boolean | null;
  active?: boolean | null;
  helpTextFa?: string | null;
  options?: {
    docs?: (number | ConfigurationOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuration-options".
 */
export interface ConfigurationOption {
  id: number;
  '_configuration-options_options_order'?: string | null;
  group: number | ConfigurationGroup;
  title: string;
  code?: string | null;
  swatchColor?: string | null;
  swatchMedia?: (number | null) | Media;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * هر گونه باید یک کد ثبت، قیمت یا تفاوت عملیاتی واقعی داشته باشد.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * محصول مادر را پیش از انتخاب گزینه‌های گونه مشخص کنید.
   */
  product: number | Product;
  nilperCode: string;
  /**
   * عنوان داخلی برای مدیریت؛ این متن به مشتری نمایش داده نمی‌شود و به‌صورت خودکار تکمیل می‌شود.
   */
  title?: string | null;
  /**
   * گزینه‌هایی را انتخاب کنید که در محصول مادر فعال شده‌اند.
   */
  options: (number | VariantOption)[];
  shippingMode?: ('parcel' | 'freight') | null;
  /**
   * وزن واقعی خود کالا؛ وزن بسته‌بندی عمومی از تنظیمات محرمانه تاپین افزوده می‌شود.
   */
  parcelWeightInGrams?: number | null;
  tapinBoxID?: number | null;
  priceInTMNEnabled?: boolean | null;
  /**
   * مبلغ را به تومان و بدون جداکننده وارد کنید.
   */
  priceInTMN?: number | null;
  /**
   * فقط اختلاف فیزیکی این کد ثبت، مانند فرم نشیمن، ابعاد، وزن یا متراژ پارچه.
   */
  measurements?:
    | {
        key: string;
        labelFa: string;
        value: number;
        unit: 'cm' | 'kg' | 'm' | 'unit';
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  manufacturingNotesFa?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        /**
         * ورودی پایدار گروه و گزینه؛ عنوان‌ها و شناسه نهایی در سرور بازنویسی می‌شوند.
         */
        configuration?:
          | {
              groupKey: string;
              group?: (number | null) | ConfigurationGroup;
              groupLabelFaSnapshot: string;
              option?: (number | null) | ConfigurationOption;
              optionCodeSnapshot?: string | null;
              labelFaSnapshot: string;
              id?: string | null;
            }[]
          | null;
        configurationKey: string;
        productTitleSnapshot: string;
        variantCodeSnapshot?: string | null;
        unitPriceInTMN: number;
        shippingModeSnapshot?: ('parcel' | 'freight') | null;
        parcelWeightInGramsSnapshot?: number | null;
        tapinBoxIDSnapshot?: number | null;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'zarinpal' | null;
  zarinpal?: {
    authority?: string | null;
    referenceID?: string | null;
    requestedAmountInRial?: number | null;
    providerCode?: number | null;
    cardPAN?: string | null;
    cardHash?: string | null;
    feeInRial?: number | null;
    feeType?: string | null;
    callbackReceivedAt?: string | null;
    verifiedAt?: string | null;
    failureMessage?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | Customer;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'TMN' | null;
  shippingMode?: ('parcel' | 'freight') | null;
  shippingAmountInTMN?: number | null;
  shippingProvider?: ('tapin' | 'manual') | null;
  shippingServiceID?: string | null;
  shippingServiceLabel?: string | null;
  shippingProvinceCode?: number | null;
  shippingCityCode?: number | null;
  shippingWeightInGrams?: number | null;
  shippingBoxID?: number | null;
  shippingQuotedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        /**
         * ورودی پایدار گروه و گزینه؛ عنوان‌ها و شناسه نهایی در سرور بازنویسی می‌شوند.
         */
        configuration?:
          | {
              groupKey: string;
              group?: (number | null) | ConfigurationGroup;
              groupLabelFaSnapshot: string;
              option?: (number | null) | ConfigurationOption;
              optionCodeSnapshot?: string | null;
              labelFaSnapshot: string;
              id?: string | null;
            }[]
          | null;
        configurationKey: string;
        productTitleSnapshot: string;
        variantCodeSnapshot?: string | null;
        unitPriceInTMN: number;
        shippingModeSnapshot?: ('parcel' | 'freight') | null;
        parcelWeightInGramsSnapshot?: number | null;
        tapinBoxIDSnapshot?: number | null;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | Customer;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'TMN' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-otp-challenges".
 */
export interface CustomerOtpChallenge {
  id: number;
  phoneKey: string;
  requestIpKey: string;
  codeHash: string;
  codeSalt: string;
  expiresAt: string;
  attempts: number;
  deliveryState: 'pending' | 'delivered' | 'failed';
  providerMessageId?: string | null;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-sessions".
 */
export interface CustomerSession {
  id: number;
  customer: number | Customer;
  tokenHash: string;
  challengeKey: string;
  expiresAt: string;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * دسته‌بندی‌های تحریریه برای گروه‌بندی و فیلتر مطالب مجله.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  published?: boolean | null;
  posts?: {
    docs?: (number | Post)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * عنوان صفحه از فیلد «عنوان» می‌آید؛ داخل متن از تیتر ۲ تا ۴ استفاده کنید. فهرست مطلب و زمان مطالعه خودکار ساخته می‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * مثال: choosing-sofa-dimensions — بعد از انتشار تغییر ندهید.
   */
  slug: string;
  category: number | BlogCategory;
  description: string;
  /**
   * پاسخ مستقیم و مستقل به پرسش اصلی مطلب؛ در صفحه نیز دیده می‌شود.
   */
  summary: string;
  /**
   * اختیاری؛ در صورت خالی بودن، جای تصویر در سایت خالی می‌ماند تا بعداً اضافه شود.
   */
  heroImage?: (number | null) | Media;
  heroCaption?: string | null;
  /**
   * برای بخش‌های اصلی H2 بگذارید؛ فهرست خودکار از H2ها ساخته می‌شود. H3 و H4 برای زیربخش‌ها هستند.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  takeaway: string;
  callToAction: {
    label: string;
    /**
     * مثال: /shop یا /contact
     */
    href: string;
  };
  relatedPosts?: (number | Post)[] | null;
  authorName: string;
  authorUrl?: string | null;
  authorBio?: string | null;
  seo?: {
    /**
     * اگر خالی باشد، عنوان اصلی استفاده می‌شود.
     */
    title?: string | null;
    /**
     * اگر خالی باشد، خلاصه کارت استفاده می‌شود.
     */
    description?: string | null;
    socialImage?: (number | null) | Media;
    /**
     * برای تمرکز تحریریه است؛ به‌عنوان meta keywords منتشر نمی‌شود.
     */
    primaryTopic?: string | null;
    /**
     * فقط برای مطالبی که نباید در نتایج جست‌وجو دیده شوند.
     */
    noIndex?: boolean | null;
  };
  /**
   * در اولین انتشار، اگر خالی باشد خودکار ثبت می‌شود.
   */
  publishedAt?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  wordCount?: number | null;
  readingTimeMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  sector: 'residential' | 'hospitality' | 'commercial' | 'workplace' | 'healthcare';
  descriptionFa: string;
  briefFa: string;
  heroMedia?: (number | null) | Media;
  heroAlt?: string | null;
  heroCaption?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  approach?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  palette?:
    | {
        name: string;
        color: string;
        id?: string | null;
      }[]
    | null;
  products?: (number | Product)[] | null;
  article?: (number | null) | Post;
  featured?: boolean | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * هر ردیف، سابقه یک عملیات خروجی و فایل قابل دانلود آن است. می‌توانید از رکوردهای انتخاب‌شده، فیلتر فعلی یا همه رکوردهای همان بخش JSON بگیرید؛ سوابق پس از ۷ روز خودکار حذف می‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * هر ردیف، سابقه یک عملیات ورود داده و نتیجه یا خطاهای آن است. فایل JSON را برای ایجاد یا به‌روزرسانی گروهی بارگذاری کنید؛ تصاویر باید پیش‌تر در رسانه‌ها باشند. سوابق پس از ۷ روز خودکار حذف می‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'cleanupDataTransferFiles' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'cleanupDataTransferFiles' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'customer-otp-challenges';
        value: number | CustomerOtpChallenge;
      } | null)
    | ({
        relationTo: 'customer-sessions';
        value: number | CustomerSession;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'product-series';
        value: number | ProductSery;
      } | null)
    | ({
        relationTo: 'configuration-groups';
        value: number | ConfigurationGroup;
      } | null)
    | ({
        relationTo: 'configuration-options';
        value: number | ConfigurationOption;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  role?: T;
  contactTitle?: T;
  contactDescription?: T;
  whatsappPhone?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  active?: T;
  addresses?: T;
  orders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-otp-challenges_select".
 */
export interface CustomerOtpChallengesSelect<T extends boolean = true> {
  phoneKey?: T;
  requestIpKey?: T;
  codeHash?: T;
  codeSalt?: T;
  expiresAt?: T;
  attempts?: T;
  deliveryState?: T;
  providerMessageId?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-sessions_select".
 */
export interface CustomerSessionsSelect<T extends boolean = true> {
  customer?: T;
  tokenHash?: T;
  challengeKey?: T;
  expiresAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  captionFa?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        adminThumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  published?: T;
  posts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  description?: T;
  summary?: T;
  heroImage?: T;
  heroCaption?: T;
  content?: T;
  takeaway?: T;
  callToAction?:
    | T
    | {
        label?: T;
        href?: T;
      };
  relatedPosts?: T;
  authorName?: T;
  authorUrl?: T;
  authorBio?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        primaryTopic?: T;
        noIndex?: T;
      };
  publishedAt?: T;
  featured?: T;
  sortOrder?: T;
  wordCount?: T;
  readingTimeMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  descriptionFa?: T;
  taglineFa?: T;
  storyFa?: T;
  logo?: T;
  heroMedia?: T;
  heroAlt?: T;
  heroCaption?: T;
  featured?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sector?: T;
  descriptionFa?: T;
  briefFa?: T;
  heroMedia?: T;
  heroAlt?: T;
  heroCaption?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  approach?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  palette?:
    | T
    | {
        name?: T;
        color?: T;
        id?: T;
      };
  products?: T;
  article?: T;
  featured?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  image?: T;
  descriptionFa?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-series_select".
 */
export interface ProductSeriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  styleFa?: T;
  descriptionFa?: T;
  heroMedia?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuration-groups_select".
 */
export interface ConfigurationGroupsSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  inputType?: T;
  required?: T;
  active?: T;
  helpTextFa?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuration-options_select".
 */
export interface ConfigurationOptionsSelect<T extends boolean = true> {
  '_configuration-options_options_order'?: T;
  group?: T;
  title?: T;
  code?: T;
  swatchColor?: T;
  swatchMedia?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  displayLabel?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  product?: T;
  nilperCode?: T;
  title?: T;
  options?: T;
  shippingMode?: T;
  parcelWeightInGrams?: T;
  tapinBoxID?: T;
  priceInTMNEnabled?: T;
  priceInTMN?: T;
  measurements?:
    | T
    | {
        key?: T;
        labelFa?: T;
        value?: T;
        unit?: T;
        sortOrder?: T;
        id?: T;
      };
  manufacturingNotesFa?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  catalogCode?: T;
  brand?: T;
  categories?: T;
  series?: T;
  salesMode?: T;
  availabilityMode?: T;
  shippingMode?: T;
  parcelWeightInGrams?: T;
  tapinBoxID?: T;
  priceInTMNEnabled?: T;
  priceInTMN?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        captionFa?: T;
        id?: T;
      };
  descriptionFa?: T;
  measurements?:
    | T
    | {
        key?: T;
        labelFa?: T;
        value?: T;
        unit?: T;
        sortOrder?: T;
        id?: T;
      };
  technicalSpecs?:
    | T
    | {
        key?: T;
        labelFa?: T;
        valueFa?: T;
        group?: T;
        sortOrder?: T;
        id?: T;
      };
  orderNotesFa?: T;
  leadTimeFa?: T;
  configurationGroups?: T;
  relatedProducts?: T;
  matchingProducts?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        configuration?:
          | T
          | {
              groupKey?: T;
              group?: T;
              groupLabelFaSnapshot?: T;
              option?: T;
              optionCodeSnapshot?: T;
              labelFaSnapshot?: T;
              id?: T;
            };
        configurationKey?: T;
        productTitleSnapshot?: T;
        variantCodeSnapshot?: T;
        unitPriceInTMN?: T;
        shippingModeSnapshot?: T;
        parcelWeightInGramsSnapshot?: T;
        tapinBoxIDSnapshot?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        configuration?:
          | T
          | {
              groupKey?: T;
              group?: T;
              groupLabelFaSnapshot?: T;
              option?: T;
              optionCodeSnapshot?: T;
              labelFaSnapshot?: T;
              id?: T;
            };
        configurationKey?: T;
        productTitleSnapshot?: T;
        variantCodeSnapshot?: T;
        unitPriceInTMN?: T;
        shippingModeSnapshot?: T;
        parcelWeightInGramsSnapshot?: T;
        tapinBoxIDSnapshot?: T;
        id?: T;
      };
  customer?: T;
  contactName?: T;
  contactPhone?: T;
  customerAddress?: T;
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  deliveryMethod?: T;
  shippingMode?: T;
  shippingAmountInTMN?: T;
  shippingProvider?: T;
  shippingServiceID?: T;
  shippingServiceLabel?: T;
  shippingProvinceCode?: T;
  shippingCityCode?: T;
  shippingWeightInGrams?: T;
  shippingBoxID?: T;
  shippingQuotedAt?: T;
  shippingStatus?: T;
  shippingShipmentID?: T;
  shippingTrackingCode?: T;
  shippingProviderStatus?: T;
  shippingFailureMessage?: T;
  shipmentCreatedAt?: T;
  amount?: T;
  currency?: T;
  paymentMethod?: T;
  paymentTransaction?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  orderNumber?: T;
  sourceCart?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        configuration?:
          | T
          | {
              groupKey?: T;
              group?: T;
              groupLabelFaSnapshot?: T;
              option?: T;
              optionCodeSnapshot?: T;
              labelFaSnapshot?: T;
              id?: T;
            };
        configurationKey?: T;
        productTitleSnapshot?: T;
        variantCodeSnapshot?: T;
        unitPriceInTMN?: T;
        shippingModeSnapshot?: T;
        parcelWeightInGramsSnapshot?: T;
        tapinBoxIDSnapshot?: T;
        id?: T;
      };
  paymentMethod?: T;
  zarinpal?:
    | T
    | {
        authority?: T;
        referenceID?: T;
        requestedAmountInRial?: T;
        providerCode?: T;
        cardPAN?: T;
        cardHash?: T;
        feeInRial?: T;
        feeType?: T;
        callbackReceivedAt?: T;
        verifiedAt?: T;
        failureMessage?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  shippingMode?: T;
  shippingAmountInTMN?: T;
  shippingProvider?: T;
  shippingServiceID?: T;
  shippingServiceLabel?: T;
  shippingProvinceCode?: T;
  shippingCityCode?: T;
  shippingWeightInGrams?: T;
  shippingBoxID?: T;
  shippingQuotedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCleanupDataTransferFiles".
 */
export interface TaskCleanupDataTransferFiles {
  input?: unknown;
  output: {
    deletedImports: number;
    deletedExports: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'customers'
      | 'customer-otp-challenges'
      | 'customer-sessions'
      | 'media'
      | 'blog-categories'
      | 'posts'
      | 'brands'
      | 'projects'
      | 'categories'
      | 'product-series'
      | 'configuration-groups'
      | 'configuration-options'
      | 'addresses'
      | 'variants'
      | 'variantTypes'
      | 'variantOptions'
      | 'products'
      | 'carts'
      | 'orders'
      | 'transactions'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}